module Integer : Integer.S = Integer
module Buffet0 = Buffet0
module Buffet1 = Buffet1
module Buffet2 = Buffet2
module Buffet3 = Buffet3
module Buffet4 = Buffet4
module Buffet6 = Buffet6
module Buffet7 = Buffet7
module Buffet8 = Buffet8
module Buffet9 = Buffet9
module Buffet10 = Buffet10
